# Generated by Django 3.0.8 on 2021-10-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
