# Generated by Django 3.0.8 on 2021-10-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='numOfLike',
        ),
    ]
